### ISSUE TITLE
SWSH grid

### ISSUE THREAD

**Issue by nilsvu** [moble/spherical#16]
Hi Mike, your `spherical_functions` package (and perhaps also an earlier version of `spherical`?) had a [`SWSH_grid`](https://github.com/moble/spherical_functions/blob/33450a285ccd69bc65171232e712fc573bb0499c/spherical_functions/SWSH/__init__.py#L48) function. Would it be reasonable to add this function here? I'd like to upgrade from `spherical_functions` to `spherical` in my [gwpv](https://github.com/nilsvu/gwpv) visualization code, which uses `SWSH_grid` to evaluate the spherical harmonics on a uniform Cartesian grid and caches the grid on disk.

**Comment by moble** [comment]
Hi Nils, I'm not sure if it's worth making a separate function.  Essentially, that function has become the [`Wigner.sYlm`](https://spherical.readthedocs.io/en/main/api/spherical/wigner/#sylm) method.  If you just want a compatibility layer, this should suffice:
```python
def SWSH_grid(R_grid, s, ell_max):
    return spherical.Wigner(ell_max).sYlm(s, R_grid)
```
It's not terrible to just create a `Wigner` object for one quick use, but I try to resist doing it inside of functions, so that I don't lull people into relying on such functions and putting them in hot loops.  So I don't think I'd put that in the package.  Does that sound reasonable?

---

BTW, in making sure that worked, I put together a working example that might also be helpful with the transition from `quaternion` to `quaternionic`:
```python
import quaternionic
import spherical

s = -2
ell_max = 8
n_theta = 2*ell_max+1
n_phi = 2*ell_max+1

wigner = spherical.Wigner(ell_max)
theta_phi_grid = spherical.theta_phi(n_theta, n_phi)
R_grid = quaternionic.array.from_spherical_coordinates(theta_phi_grid)

sYlm_grid = wigner.sYlm(s, R_grid)
```
